//go:build !ignore_autogenerated

/*
Copyright 2025 Flant JSC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUCapabilities) DeepCopyInto(out *GPUCapabilities) {
	*out = *in
	if in.MemoryMiB != nil {
		in, out := &in.MemoryMiB, &out.MemoryMiB
		*out = new(int64)
		**out = **in
	}
	if in.Vendor != nil {
		in, out := &in.Vendor, &out.Vendor
		*out = new(GPUVendorCapabilities)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUCapabilities.
func (in *GPUCapabilities) DeepCopy() *GPUCapabilities {
	if in == nil {
		return nil
	}
	out := new(GPUCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUClass) DeepCopyInto(out *GPUClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUClass.
func (in *GPUClass) DeepCopy() *GPUClass {
	if in == nil {
		return nil
	}
	out := new(GPUClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUClassGeneratedStatus) DeepCopyInto(out *GPUClassGeneratedStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUClassGeneratedStatus.
func (in *GPUClassGeneratedStatus) DeepCopy() *GPUClassGeneratedStatus {
	if in == nil {
		return nil
	}
	out := new(GPUClassGeneratedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUClassList) DeepCopyInto(out *GPUClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUClassList.
func (in *GPUClassList) DeepCopy() *GPUClassList {
	if in == nil {
		return nil
	}
	out := new(GPUClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUClassMIGSpec) DeepCopyInto(out *GPUClassMIGSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUClassMIGSpec.
func (in *GPUClassMIGSpec) DeepCopy() *GPUClassMIGSpec {
	if in == nil {
		return nil
	}
	out := new(GPUClassMIGSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUClassNvidiaSpec) DeepCopyInto(out *GPUClassNvidiaSpec) {
	*out = *in
	if in.MIG != nil {
		in, out := &in.MIG, &out.MIG
		*out = new(GPUClassMIGSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUClassNvidiaSpec.
func (in *GPUClassNvidiaSpec) DeepCopy() *GPUClassNvidiaSpec {
	if in == nil {
		return nil
	}
	out := new(GPUClassNvidiaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUClassRequirements) DeepCopyInto(out *GPUClassRequirements) {
	*out = *in
	if in.MinMemory != nil {
		in, out := &in.MinMemory, &out.MinMemory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUClassRequirements.
func (in *GPUClassRequirements) DeepCopy() *GPUClassRequirements {
	if in == nil {
		return nil
	}
	out := new(GPUClassRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUClassSpec) DeepCopyInto(out *GPUClassSpec) {
	*out = *in
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = new(GPUClassRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Nvidia != nil {
		in, out := &in.Nvidia, &out.Nvidia
		*out = new(GPUClassNvidiaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Sharing != nil {
		in, out := &in.Sharing, &out.Sharing
		*out = new(GPUSharing)
		(*in).DeepCopyInto(*out)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUClassSpec.
func (in *GPUClassSpec) DeepCopy() *GPUClassSpec {
	if in == nil {
		return nil
	}
	out := new(GPUClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUClassStatus) DeepCopyInto(out *GPUClassStatus) {
	*out = *in
	if in.Valid != nil {
		in, out := &in.Valid, &out.Valid
		*out = new(bool)
		**out = **in
	}
	if in.Generated != nil {
		in, out := &in.Generated, &out.Generated
		*out = new(GPUClassGeneratedStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUClassStatus.
func (in *GPUClassStatus) DeepCopy() *GPUClassStatus {
	if in == nil {
		return nil
	}
	out := new(GPUClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUCurrentState) DeepCopyInto(out *GPUCurrentState) {
	*out = *in
	if in.Nvidia != nil {
		in, out := &in.Nvidia, &out.Nvidia
		*out = new(NvidiaCurrentState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUCurrentState.
func (in *GPUCurrentState) DeepCopy() *GPUCurrentState {
	if in == nil {
		return nil
	}
	out := new(GPUCurrentState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUSharing) DeepCopyInto(out *GPUSharing) {
	*out = *in
	if in.TimeSlicing != nil {
		in, out := &in.TimeSlicing, &out.TimeSlicing
		*out = new(TimeSlicingConfig)
		**out = **in
	}
	if in.MPS != nil {
		in, out := &in.MPS, &out.MPS
		*out = new(MPSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUSharing.
func (in *GPUSharing) DeepCopy() *GPUSharing {
	if in == nil {
		return nil
	}
	out := new(GPUSharing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUVendorCapabilities) DeepCopyInto(out *GPUVendorCapabilities) {
	*out = *in
	if in.Nvidia != nil {
		in, out := &in.Nvidia, &out.Nvidia
		*out = new(NvidiaCapabilities)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUVendorCapabilities.
func (in *GPUVendorCapabilities) DeepCopy() *GPUVendorCapabilities {
	if in == nil {
		return nil
	}
	out := new(GPUVendorCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPSConfig) DeepCopyInto(out *MPSConfig) {
	*out = *in
	if in.DefaultActiveThreadPercentage != nil {
		in, out := &in.DefaultActiveThreadPercentage, &out.DefaultActiveThreadPercentage
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPSConfig.
func (in *MPSConfig) DeepCopy() *MPSConfig {
	if in == nil {
		return nil
	}
	out := new(MPSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInfo) DeepCopyInto(out *NodeInfo) {
	*out = *in
	if in.OS != nil {
		in, out := &in.OS, &out.OS
		*out = new(OSInfo)
		**out = **in
	}
	if in.BareMetal != nil {
		in, out := &in.BareMetal, &out.BareMetal
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInfo.
func (in *NodeInfo) DeepCopy() *NodeInfo {
	if in == nil {
		return nil
	}
	out := new(NodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NvidiaCapabilities) DeepCopyInto(out *NvidiaCapabilities) {
	*out = *in
	if in.ComputeTypes != nil {
		in, out := &in.ComputeTypes, &out.ComputeTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MIGSupported != nil {
		in, out := &in.MIGSupported, &out.MIGSupported
		*out = new(bool)
		**out = **in
	}
	if in.MIG != nil {
		in, out := &in.MIG, &out.MIG
		*out = new(NvidiaMIGCapabilities)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NvidiaCapabilities.
func (in *NvidiaCapabilities) DeepCopy() *NvidiaCapabilities {
	if in == nil {
		return nil
	}
	out := new(NvidiaCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NvidiaCurrentState) DeepCopyInto(out *NvidiaCurrentState) {
	*out = *in
	if in.MIG != nil {
		in, out := &in.MIG, &out.MIG
		*out = new(NvidiaMIGState)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NvidiaCurrentState.
func (in *NvidiaCurrentState) DeepCopy() *NvidiaCurrentState {
	if in == nil {
		return nil
	}
	out := new(NvidiaCurrentState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NvidiaMIGCapabilities) DeepCopyInto(out *NvidiaMIGCapabilities) {
	*out = *in
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]NvidiaMIGProfile, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NvidiaMIGCapabilities.
func (in *NvidiaMIGCapabilities) DeepCopy() *NvidiaMIGCapabilities {
	if in == nil {
		return nil
	}
	out := new(NvidiaMIGCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NvidiaMIGProfile) DeepCopyInto(out *NvidiaMIGProfile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NvidiaMIGProfile.
func (in *NvidiaMIGProfile) DeepCopy() *NvidiaMIGProfile {
	if in == nil {
		return nil
	}
	out := new(NvidiaMIGProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NvidiaMIGState) DeepCopyInto(out *NvidiaMIGState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NvidiaMIGState.
func (in *NvidiaMIGState) DeepCopy() *NvidiaMIGState {
	if in == nil {
		return nil
	}
	out := new(NvidiaMIGState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OSInfo) DeepCopyInto(out *OSInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OSInfo.
func (in *OSInfo) DeepCopy() *OSInfo {
	if in == nil {
		return nil
	}
	out := new(OSInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCIClassInfo) DeepCopyInto(out *PCIClassInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCIClassInfo.
func (in *PCIClassInfo) DeepCopy() *PCIClassInfo {
	if in == nil {
		return nil
	}
	out := new(PCIClassInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCIDeviceInfo) DeepCopyInto(out *PCIDeviceInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCIDeviceInfo.
func (in *PCIDeviceInfo) DeepCopy() *PCIDeviceInfo {
	if in == nil {
		return nil
	}
	out := new(PCIDeviceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCIInfo) DeepCopyInto(out *PCIInfo) {
	*out = *in
	if in.Class != nil {
		in, out := &in.Class, &out.Class
		*out = new(PCIClassInfo)
		**out = **in
	}
	if in.Vendor != nil {
		in, out := &in.Vendor, &out.Vendor
		*out = new(PCIVendorInfo)
		**out = **in
	}
	if in.Device != nil {
		in, out := &in.Device, &out.Device
		*out = new(PCIDeviceInfo)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCIInfo.
func (in *PCIInfo) DeepCopy() *PCIInfo {
	if in == nil {
		return nil
	}
	out := new(PCIInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCIVendorInfo) DeepCopyInto(out *PCIVendorInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCIVendorInfo.
func (in *PCIVendorInfo) DeepCopy() *PCIVendorInfo {
	if in == nil {
		return nil
	}
	out := new(PCIVendorInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalGPU) DeepCopyInto(out *PhysicalGPU) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalGPU.
func (in *PhysicalGPU) DeepCopy() *PhysicalGPU {
	if in == nil {
		return nil
	}
	out := new(PhysicalGPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PhysicalGPU) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalGPUList) DeepCopyInto(out *PhysicalGPUList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PhysicalGPU, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalGPUList.
func (in *PhysicalGPUList) DeepCopy() *PhysicalGPUList {
	if in == nil {
		return nil
	}
	out := new(PhysicalGPUList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PhysicalGPUList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalGPUSpec) DeepCopyInto(out *PhysicalGPUSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalGPUSpec.
func (in *PhysicalGPUSpec) DeepCopy() *PhysicalGPUSpec {
	if in == nil {
		return nil
	}
	out := new(PhysicalGPUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalGPUStatus) DeepCopyInto(out *PhysicalGPUStatus) {
	*out = *in
	if in.NodeInfo != nil {
		in, out := &in.NodeInfo, &out.NodeInfo
		*out = new(NodeInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.PCIInfo != nil {
		in, out := &in.PCIInfo, &out.PCIInfo
		*out = new(PCIInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(GPUCapabilities)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentState != nil {
		in, out := &in.CurrentState, &out.CurrentState
		*out = new(GPUCurrentState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalGPUStatus.
func (in *PhysicalGPUStatus) DeepCopy() *PhysicalGPUStatus {
	if in == nil {
		return nil
	}
	out := new(PhysicalGPUStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeSlicingConfig) DeepCopyInto(out *TimeSlicingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeSlicingConfig.
func (in *TimeSlicingConfig) DeepCopy() *TimeSlicingConfig {
	if in == nil {
		return nil
	}
	out := new(TimeSlicingConfig)
	in.DeepCopyInto(out)
	return out
}
