//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGPUPool) DeepCopyInto(out *ClusterGPUPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGPUPool.
func (in *ClusterGPUPool) DeepCopy() *ClusterGPUPool {
	if in == nil {
		return nil
	}
	out := new(ClusterGPUPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGPUPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterGPUPoolList) DeepCopyInto(out *ClusterGPUPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterGPUPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterGPUPoolList.
func (in *ClusterGPUPoolList) DeepCopy() *ClusterGPUPoolList {
	if in == nil {
		return nil
	}
	out := new(ClusterGPUPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterGPUPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUComputeCapability) DeepCopyInto(out *GPUComputeCapability) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUComputeCapability.
func (in *GPUComputeCapability) DeepCopy() *GPUComputeCapability {
	if in == nil {
		return nil
	}
	out := new(GPUComputeCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDevice) DeepCopyInto(out *GPUDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDevice.
func (in *GPUDevice) DeepCopy() *GPUDevice {
	if in == nil {
		return nil
	}
	out := new(GPUDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDeviceHardware) DeepCopyInto(out *GPUDeviceHardware) {
	*out = *in
	out.PCI = in.PCI
	if in.NUMANode != nil {
		in, out := &in.NUMANode, &out.NUMANode
		*out = new(int32)
		**out = **in
	}
	if in.PowerLimitMilliWatt != nil {
		in, out := &in.PowerLimitMilliWatt, &out.PowerLimitMilliWatt
		*out = new(int32)
		**out = **in
	}
	if in.SMCount != nil {
		in, out := &in.SMCount, &out.SMCount
		*out = new(int32)
		**out = **in
	}
	if in.MemoryBandwidthMiB != nil {
		in, out := &in.MemoryBandwidthMiB, &out.MemoryBandwidthMiB
		*out = new(int32)
		**out = **in
	}
	in.PCIE.DeepCopyInto(&out.PCIE)
	if in.ComputeCapability != nil {
		in, out := &in.ComputeCapability, &out.ComputeCapability
		*out = new(GPUComputeCapability)
		**out = **in
	}
	in.Precision.DeepCopyInto(&out.Precision)
	in.MIG.DeepCopyInto(&out.MIG)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDeviceHardware.
func (in *GPUDeviceHardware) DeepCopy() *GPUDeviceHardware {
	if in == nil {
		return nil
	}
	out := new(GPUDeviceHardware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDeviceHealth) DeepCopyInto(out *GPUDeviceHealth) {
	*out = *in
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
	if in.LastHealthyTime != nil {
		in, out := &in.LastHealthyTime, &out.LastHealthyTime
		*out = (*in).DeepCopy()
	}
	if in.LastErrorTime != nil {
		in, out := &in.LastErrorTime, &out.LastErrorTime
		*out = (*in).DeepCopy()
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDeviceHealth.
func (in *GPUDeviceHealth) DeepCopy() *GPUDeviceHealth {
	if in == nil {
		return nil
	}
	out := new(GPUDeviceHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDeviceList) DeepCopyInto(out *GPUDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDeviceList.
func (in *GPUDeviceList) DeepCopy() *GPUDeviceList {
	if in == nil {
		return nil
	}
	out := new(GPUDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDeviceSpec) DeepCopyInto(out *GPUDeviceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDeviceSpec.
func (in *GPUDeviceSpec) DeepCopy() *GPUDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(GPUDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDeviceStatus) DeepCopyInto(out *GPUDeviceStatus) {
	*out = *in
	if in.PoolRef != nil {
		in, out := &in.PoolRef, &out.PoolRef
		*out = new(GPUPoolReference)
		**out = **in
	}
	in.Hardware.DeepCopyInto(&out.Hardware)
	in.Health.DeepCopyInto(&out.Health)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDeviceStatus.
func (in *GPUDeviceStatus) DeepCopy() *GPUDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(GPUDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMIGConfig) DeepCopyInto(out *GPUMIGConfig) {
	*out = *in
	if in.ProfilesSupported != nil {
		in, out := &in.ProfilesSupported, &out.ProfilesSupported
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make([]GPUMIGTypeCapacity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMIGConfig.
func (in *GPUMIGConfig) DeepCopy() *GPUMIGConfig {
	if in == nil {
		return nil
	}
	out := new(GPUMIGConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMIGEngines) DeepCopyInto(out *GPUMIGEngines) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMIGEngines.
func (in *GPUMIGEngines) DeepCopy() *GPUMIGEngines {
	if in == nil {
		return nil
	}
	out := new(GPUMIGEngines)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMIGPartition) DeepCopyInto(out *GPUMIGPartition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMIGPartition.
func (in *GPUMIGPartition) DeepCopy() *GPUMIGPartition {
	if in == nil {
		return nil
	}
	out := new(GPUMIGPartition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMIGTypeCapacity) DeepCopyInto(out *GPUMIGTypeCapacity) {
	*out = *in
	out.Partition = in.Partition
	out.Engines = in.Engines
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMIGTypeCapacity.
func (in *GPUMIGTypeCapacity) DeepCopy() *GPUMIGTypeCapacity {
	if in == nil {
		return nil
	}
	out := new(GPUMIGTypeCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeBootstrapStatus) DeepCopyInto(out *GPUNodeBootstrapStatus) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastRun != nil {
		in, out := &in.LastRun, &out.LastRun
		*out = (*in).DeepCopy()
	}
	if in.Workloads != nil {
		in, out := &in.Workloads, &out.Workloads
		*out = make([]GPUNodeBootstrapWorkloadStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PendingDevices != nil {
		in, out := &in.PendingDevices, &out.PendingDevices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Validations != nil {
		in, out := &in.Validations, &out.Validations
		*out = make([]GPUNodeValidationState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeBootstrapStatus.
func (in *GPUNodeBootstrapStatus) DeepCopy() *GPUNodeBootstrapStatus {
	if in == nil {
		return nil
	}
	out := new(GPUNodeBootstrapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeBootstrapWorkloadStatus) DeepCopyInto(out *GPUNodeBootstrapWorkloadStatus) {
	*out = *in
	if in.Since != nil {
		in, out := &in.Since, &out.Since
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeBootstrapWorkloadStatus.
func (in *GPUNodeBootstrapWorkloadStatus) DeepCopy() *GPUNodeBootstrapWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(GPUNodeBootstrapWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeDevice) DeepCopyInto(out *GPUNodeDevice) {
	*out = *in
	out.PCI = in.PCI
	if in.NUMANode != nil {
		in, out := &in.NUMANode, &out.NUMANode
		*out = new(int32)
		**out = **in
	}
	in.MIG.DeepCopyInto(&out.MIG)
	if in.ComputeCap != nil {
		in, out := &in.ComputeCap, &out.ComputeCap
		*out = new(GPUComputeCapability)
		**out = **in
	}
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeDevice.
func (in *GPUNodeDevice) DeepCopy() *GPUNodeDevice {
	if in == nil {
		return nil
	}
	out := new(GPUNodeDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeDriver) DeepCopyInto(out *GPUNodeDriver) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeDriver.
func (in *GPUNodeDriver) DeepCopy() *GPUNodeDriver {
	if in == nil {
		return nil
	}
	out := new(GPUNodeDriver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeHardware) DeepCopyInto(out *GPUNodeHardware) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeHardware.
func (in *GPUNodeHardware) DeepCopy() *GPUNodeHardware {
	if in == nil {
		return nil
	}
	out := new(GPUNodeHardware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeInventory) DeepCopyInto(out *GPUNodeInventory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeInventory.
func (in *GPUNodeInventory) DeepCopy() *GPUNodeInventory {
	if in == nil {
		return nil
	}
	out := new(GPUNodeInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNodeInventory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeInventoryList) DeepCopyInto(out *GPUNodeInventoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUNodeInventory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeInventoryList.
func (in *GPUNodeInventoryList) DeepCopy() *GPUNodeInventoryList {
	if in == nil {
		return nil
	}
	out := new(GPUNodeInventoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUNodeInventoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeInventorySpec) DeepCopyInto(out *GPUNodeInventorySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeInventorySpec.
func (in *GPUNodeInventorySpec) DeepCopy() *GPUNodeInventorySpec {
	if in == nil {
		return nil
	}
	out := new(GPUNodeInventorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeInventoryStatus) DeepCopyInto(out *GPUNodeInventoryStatus) {
	*out = *in
	in.Hardware.DeepCopyInto(&out.Hardware)
	out.Driver = in.Driver
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]GPUNodeDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	in.Bootstrap.DeepCopyInto(&out.Bootstrap)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeInventoryStatus.
func (in *GPUNodeInventoryStatus) DeepCopy() *GPUNodeInventoryStatus {
	if in == nil {
		return nil
	}
	out := new(GPUNodeInventoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeMonitoring) DeepCopyInto(out *GPUNodeMonitoring) {
	*out = *in
	if in.LastHeartbeat != nil {
		in, out := &in.LastHeartbeat, &out.LastHeartbeat
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeMonitoring.
func (in *GPUNodeMonitoring) DeepCopy() *GPUNodeMonitoring {
	if in == nil {
		return nil
	}
	out := new(GPUNodeMonitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUNodeValidationState) DeepCopyInto(out *GPUNodeValidationState) {
	*out = *in
	if in.LastFailure != nil {
		in, out := &in.LastFailure, &out.LastFailure
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUNodeValidationState.
func (in *GPUNodeValidationState) DeepCopy() *GPUNodeValidationState {
	if in == nil {
		return nil
	}
	out := new(GPUNodeValidationState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPool) DeepCopyInto(out *GPUPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPool.
func (in *GPUPool) DeepCopy() *GPUPool {
	if in == nil {
		return nil
	}
	out := new(GPUPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolAssignment) DeepCopyInto(out *GPUPoolAssignment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolAssignment.
func (in *GPUPoolAssignment) DeepCopy() *GPUPoolAssignment {
	if in == nil {
		return nil
	}
	out := new(GPUPoolAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolAssignmentSpec) DeepCopyInto(out *GPUPoolAssignmentSpec) {
	*out = *in
	if in.AutoApproveSelector != nil {
		in, out := &in.AutoApproveSelector, &out.AutoApproveSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolAssignmentSpec.
func (in *GPUPoolAssignmentSpec) DeepCopy() *GPUPoolAssignmentSpec {
	if in == nil {
		return nil
	}
	out := new(GPUPoolAssignmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolCandidate) DeepCopyInto(out *GPUPoolCandidate) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]GPUPoolAssignment, len(*in))
		copy(*out, *in)
	}
	if in.LastEvent != nil {
		in, out := &in.LastEvent, &out.LastEvent
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolCandidate.
func (in *GPUPoolCandidate) DeepCopy() *GPUPoolCandidate {
	if in == nil {
		return nil
	}
	out := new(GPUPoolCandidate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolCapacityStatus) DeepCopyInto(out *GPUPoolCapacityStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolCapacityStatus.
func (in *GPUPoolCapacityStatus) DeepCopy() *GPUPoolCapacityStatus {
	if in == nil {
		return nil
	}
	out := new(GPUPoolCapacityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolDeviceSelector) DeepCopyInto(out *GPUPoolDeviceSelector) {
	*out = *in
	in.Include.DeepCopyInto(&out.Include)
	in.Exclude.DeepCopyInto(&out.Exclude)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolDeviceSelector.
func (in *GPUPoolDeviceSelector) DeepCopy() *GPUPoolDeviceSelector {
	if in == nil {
		return nil
	}
	out := new(GPUPoolDeviceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolDeviceStatus) DeepCopyInto(out *GPUPoolDeviceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolDeviceStatus.
func (in *GPUPoolDeviceStatus) DeepCopy() *GPUPoolDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(GPUPoolDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolList) DeepCopyInto(out *GPUPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolList.
func (in *GPUPoolList) DeepCopy() *GPUPoolList {
	if in == nil {
		return nil
	}
	out := new(GPUPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolMIGDeviceLayout) DeepCopyInto(out *GPUPoolMIGDeviceLayout) {
	*out = *in
	if in.UUIDs != nil {
		in, out := &in.UUIDs, &out.UUIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCIBusIDs != nil {
		in, out := &in.PCIBusIDs, &out.PCIBusIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeviceFilter != nil {
		in, out := &in.DeviceFilter, &out.DeviceFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make([]GPUPoolMIGProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SlicesPerUnit != nil {
		in, out := &in.SlicesPerUnit, &out.SlicesPerUnit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolMIGDeviceLayout.
func (in *GPUPoolMIGDeviceLayout) DeepCopy() *GPUPoolMIGDeviceLayout {
	if in == nil {
		return nil
	}
	out := new(GPUPoolMIGDeviceLayout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolMIGProfile) DeepCopyInto(out *GPUPoolMIGProfile) {
	*out = *in
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(int32)
		**out = **in
	}
	if in.SlicesPerUnit != nil {
		in, out := &in.SlicesPerUnit, &out.SlicesPerUnit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolMIGProfile.
func (in *GPUPoolMIGProfile) DeepCopy() *GPUPoolMIGProfile {
	if in == nil {
		return nil
	}
	out := new(GPUPoolMIGProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolNodeStatus) DeepCopyInto(out *GPUPoolNodeStatus) {
	*out = *in
	if in.LastEvent != nil {
		in, out := &in.LastEvent, &out.LastEvent
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolNodeStatus.
func (in *GPUPoolNodeStatus) DeepCopy() *GPUPoolNodeStatus {
	if in == nil {
		return nil
	}
	out := new(GPUPoolNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolReference) DeepCopyInto(out *GPUPoolReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolReference.
func (in *GPUPoolReference) DeepCopy() *GPUPoolReference {
	if in == nil {
		return nil
	}
	out := new(GPUPoolReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolResourceSpec) DeepCopyInto(out *GPUPoolResourceSpec) {
	*out = *in
	if in.MIGLayout != nil {
		in, out := &in.MIGLayout, &out.MIGLayout
		*out = make([]GPUPoolMIGDeviceLayout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaxDevicesPerNode != nil {
		in, out := &in.MaxDevicesPerNode, &out.MaxDevicesPerNode
		*out = new(int32)
		**out = **in
	}
	if in.TimeSlicingResources != nil {
		in, out := &in.TimeSlicingResources, &out.TimeSlicingResources
		*out = make([]GPUPoolTimeSlicingResource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolResourceSpec.
func (in *GPUPoolResourceSpec) DeepCopy() *GPUPoolResourceSpec {
	if in == nil {
		return nil
	}
	out := new(GPUPoolResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolSchedulingSpec) DeepCopyInto(out *GPUPoolSchedulingSpec) {
	*out = *in
	if in.TaintsEnabled != nil {
		in, out := &in.TaintsEnabled, &out.TaintsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]GPUPoolTaintSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolSchedulingSpec.
func (in *GPUPoolSchedulingSpec) DeepCopy() *GPUPoolSchedulingSpec {
	if in == nil {
		return nil
	}
	out := new(GPUPoolSchedulingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolSelectorRules) DeepCopyInto(out *GPUPoolSelectorRules) {
	*out = *in
	if in.InventoryIDs != nil {
		in, out := &in.InventoryIDs, &out.InventoryIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Products != nil {
		in, out := &in.Products, &out.Products
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCIVendors != nil {
		in, out := &in.PCIVendors, &out.PCIVendors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PCIDevices != nil {
		in, out := &in.PCIDevices, &out.PCIDevices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MIGCapable != nil {
		in, out := &in.MIGCapable, &out.MIGCapable
		*out = new(bool)
		**out = **in
	}
	if in.MIGProfiles != nil {
		in, out := &in.MIGProfiles, &out.MIGProfiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolSelectorRules.
func (in *GPUPoolSelectorRules) DeepCopy() *GPUPoolSelectorRules {
	if in == nil {
		return nil
	}
	out := new(GPUPoolSelectorRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolSpec) DeepCopyInto(out *GPUPoolSpec) {
	*out = *in
	in.Resource.DeepCopyInto(&out.Resource)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DeviceSelector != nil {
		in, out := &in.DeviceSelector, &out.DeviceSelector
		*out = new(GPUPoolDeviceSelector)
		(*in).DeepCopyInto(*out)
	}
	in.DeviceAssignment.DeepCopyInto(&out.DeviceAssignment)
	in.Scheduling.DeepCopyInto(&out.Scheduling)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolSpec.
func (in *GPUPoolSpec) DeepCopy() *GPUPoolSpec {
	if in == nil {
		return nil
	}
	out := new(GPUPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolStatus) DeepCopyInto(out *GPUPoolStatus) {
	*out = *in
	out.Capacity = in.Capacity
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]GPUPoolNodeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Candidates != nil {
		in, out := &in.Candidates, &out.Candidates
		*out = make([]GPUPoolCandidate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]GPUPoolDeviceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolStatus.
func (in *GPUPoolStatus) DeepCopy() *GPUPoolStatus {
	if in == nil {
		return nil
	}
	out := new(GPUPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolTaintSpec) DeepCopyInto(out *GPUPoolTaintSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolTaintSpec.
func (in *GPUPoolTaintSpec) DeepCopy() *GPUPoolTaintSpec {
	if in == nil {
		return nil
	}
	out := new(GPUPoolTaintSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPoolTimeSlicingResource) DeepCopyInto(out *GPUPoolTimeSlicingResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPoolTimeSlicingResource.
func (in *GPUPoolTimeSlicingResource) DeepCopy() *GPUPoolTimeSlicingResource {
	if in == nil {
		return nil
	}
	out := new(GPUPoolTimeSlicingResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUPrecision) DeepCopyInto(out *GPUPrecision) {
	*out = *in
	if in.Supported != nil {
		in, out := &in.Supported, &out.Supported
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUPrecision.
func (in *GPUPrecision) DeepCopy() *GPUPrecision {
	if in == nil {
		return nil
	}
	out := new(GPUPrecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCIAddress) DeepCopyInto(out *PCIAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCIAddress.
func (in *PCIAddress) DeepCopy() *PCIAddress {
	if in == nil {
		return nil
	}
	out := new(PCIAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCIELink) DeepCopyInto(out *PCIELink) {
	*out = *in
	if in.Generation != nil {
		in, out := &in.Generation, &out.Generation
		*out = new(int32)
		**out = **in
	}
	if in.Width != nil {
		in, out := &in.Width, &out.Width
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCIELink.
func (in *PCIELink) DeepCopy() *PCIELink {
	if in == nil {
		return nil
	}
	out := new(PCIELink)
	in.DeepCopyInto(out)
	return out
}
