{{/* Copyright 2025 Flant JSC */}}
{{- if and (eq (include "gpuControlPlane.isEnabled" .) "true") (.Values.gpuControlPlane.monitoring.serviceMonitor) (.Values.global.enabledModules | has "operator-prometheus-crd") }}
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: {{ include "gpuControlPlane.controllerName" . }}
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.controllerName" .) "prometheus" "main")) | nindent 2 }}
spec:
  honorLabels: true
  authorization:
    credentials:
      name: prometheus-token
      key: token
  scheme: HTTPS
  tlsConfig:
    insecureSkipVerify: true
  metricsPath: /metrics
  staticConfigs:
    - targets:
        - '{{ include "gpuControlPlane.controllerName" . }}-metrics.{{ include "gpuControlPlane.namespace" . }}.svc.{{ .Values.global.discovery.clusterDomain }}.:8080'
{{- end }}
