{{- if eq (include "gpuControlPlane.isEnabled" .) "true" }}
{{- $ns := include "gpuControlPlane.namespace" . }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.controllerName" .))) | nindent 2 }}
  name: {{ include "gpuControlPlane.controllerName" . }}-defaulter
webhooks:
  - name: gpupool.gpu-control-plane.deckhouse.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: IfNeeded
    rules:
      - apiGroups:   ["gpu.deckhouse.io"]
        apiVersions: ["v1alpha1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["gpupools"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: {{ $ns }}
        name: {{ include "gpuControlPlane.controllerName" . }}
        path: /mutate-gpu-deckhouse-io-v1alpha1-gpupool
        port: 443
      caBundle: |
        {{ .Values.gpuControlPlane.internal.controller.cert.ca | b64enc }}
  - name: pod.gpu-control-plane.deckhouse.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    reinvocationPolicy: IfNeeded
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["pods"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: {{ $ns }}
        name: {{ include "gpuControlPlane.controllerName" . }}
        path: /mutate-v1-pod-gpupool
        port: 443
      caBundle: |
        {{ .Values.gpuControlPlane.internal.controller.cert.ca | b64enc }}
{{- end }}
