{{/* Copyright 2025 Flant JSC */}}
{{- if eq (include "gpuControlPlane.isEnabled" .) "true" }}
{{- $moduleValues := .Values.gpuControlPlane | default dict }}
{{- $internal := $moduleValues.internal | default dict }}
{{- $controller := $internal.controller | default dict }}
{{- $controllerCert := $controller.cert | default dict }}
{{- $controllerData := dict }}
{{- if $controllerCert.ca }}
  {{- $_ := set $controllerData "ca.crt" (printf "%s" $controllerCert.ca | b64enc) }}
{{- end }}
{{- if $controllerCert.crt }}
  {{- $_ := set $controllerData "tls.crt" (printf "%s" $controllerCert.crt | b64enc) }}
{{- end }}
{{- if $controllerCert.key }}
  {{- $_ := set $controllerData "tls.key" (printf "%s" $controllerCert.key | b64enc) }}
{{- end }}
{{- if gt (len $controllerData) 0 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpuControlPlane.controllerTLSSecretName" . }}
  namespace: {{ include "gpuControlPlane.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.controllerName" .))) | nindent 2 }}
type: kubernetes.io/tls
data:
  {{- toYaml $controllerData | nindent 2 }}
{{- end }}
{{- $metrics := $internal.metrics | default dict }}
{{- $metricsCert := $metrics.cert | default dict }}
{{- $metricsData := dict }}
{{- if $metricsCert.ca }}
  {{- $_ := set $metricsData "ca.crt" (printf "%s" $metricsCert.ca | b64enc) }}
{{- end }}
{{- if $metricsCert.crt }}
  {{- $_ := set $metricsData "tls.crt" (printf "%s" $metricsCert.crt | b64enc) }}
{{- end }}
{{- if $metricsCert.key }}
  {{- $_ := set $metricsData "tls.key" (printf "%s" $metricsCert.key | b64enc) }}
{{- end }}
{{- if gt (len $metricsData) 0 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpuControlPlane.metricsTLSSecretName" . }}
  namespace: {{ include "gpuControlPlane.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.controllerName" .))) | nindent 2 }}
type: kubernetes.io/tls
data:
  {{- toYaml $metricsData | nindent 2 }}
{{- end }}
{{- end }}
