{
 "title": "Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(max(DCGM_FI_DEV_POWER_USAGE{}) by(Hostname, device))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "GPU Pool used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\"}) / (count(DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\"}) * 100)) * 100",
     "legendFormat": "GPU Used"
    }
   ]
  },
  {
   "title": "GPU pool Memory Bandwidth Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(DCGM_FI_DEV_MEM_COPY_UTIL) / (count(DCGM_FI_DEV_MEM_COPY_UTIL) * 100)) * 100",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}