{
 "title": "GPU Namespace Pods",
 "tags": [ "GPU" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(namespace_service_account:kube_pod_info:, cluster)"
   },
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(DCGM_FI_DEV_GPU_UTIL, namespace)"
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "table",
   "description": "Сводная таблица утилизации GPU по подам\n\nРесурсы GPU запрашиваются использую PodSpec K8s для ресурса типа `nvidia.com/gpu`",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(label_replace((DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\", pod=\"$pod\"}), \"pod\", \"$1\", \"pod\", \"(.+)\")) by (pod)",
     "legendFormat": "GPU Utilization"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",resource=\"nvidia_com_gpu\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"nvidia_com_gpu\", pod=\"$pod\"}) by (pod) - sum(label_replace((DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\", pod=\"$pod\"}/100), \"pod\", \"$1\", \"pod\", \"(.+)\")) by (pod)",
     "legendFormat": "Over-requested"
    },
    {
     "expr": "sum(label_replace((DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\", pod=\"$pod\"}/100), \"pod\", \"$1\", \"pod\", \"(.+)\")) by (pod) - sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=\"$pod\", resource=\"nvidia_com_gpu\"}) by (pod) > 0 or vector(0)",
     "legendFormat": "Under-requested"
    },
    {
     "expr": "sum(label_replace(DCGM_FI_DEV_MEM_COPY_UTIL{namespace=~\"$namespace\", pod=\"$pod\"}, \"pod\", \"$1\", \"pod\", \"(.+)\")) by (pod)",
     "legendFormat": "GPU Memory Utilization"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "description": "Утилизация вычислительных едениц",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\", pod=\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{pod=\"$pod\", namespace=\"$namespace\"}) by(pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_MEM_COPY_UTIL{namespace=\"$namespace\", pod=\"$pod\"}) by(pod) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Over-requested",
   "type": "timeseries",
   "description": "Кол-во вычислительных едениц `nvidia.com/gpu` свыше используемых",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"nvidia_com_gpu\", pod=\"$pod\"}) by (pod) - sum(label_replace((DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\", pod=\"$pod\"}/100), \"pod\", \"$1\", \"pod\", \"(.+)\")) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under-requested",
   "type": "timeseries",
   "description": "Кол-во используемых едениц `nvidia.com/gpu` свыше запрошеных",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "targets": [
    {
     "expr": "sum(label_replace((DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"}/100), \"pod\", \"$1\", \"pod\", \"(.+)\")) by (pod) - sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"nvidia_com_gpu\"}) by (pod) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCIe ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU PCIe Receive",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_PROF_PCIE_RX_BYTES{namespace=\"$namespace\", pod=\"$pod\"}) by(pod, pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU PCIe Receive",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_PROF_PCIE_TX_BYTES{namespace=\"$namespace\", pod=\"$pod\"}) by(pod )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SM Clock",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU SM Clock",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_SM_CLOCK{namespace=\"$namespace\", pod=\"$pod\"}) by(pod) * 1000000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Memory Clock",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_MEM_CLOCK{namespace=\"$namespace\", pod=\"$pod\"}) by(pod) * 1000000",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}