{
 "title": "GPU Nodes",
 "tags": [ "GPU" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(DCGM_FI_DEV_POWER_USAGE,Hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "table",
   "description": "Сводная таблица утилизации GPU по устройствам\n\nРесурсы GPU запрашиваются использую PodSpec K8s для ресурса типа `nvidia.com/gpu`",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL) by (Hostname) / count(sum(DCGM_FI_DEV_GPU_UTIL) by(Hostname, device)) by(Hostname)",
     "legendFormat": "GPU Utilization"
    },
    {
     "expr": "sum(DCGM_FI_DEV_SM_CLOCK * 1000000) by (Hostname)",
     "legendFormat": "GPU SM Clock"
    },
    {
     "expr": "sum(DCGM_FI_DEV_MEM_CLOCK * 1000000) by (Hostname)",
     "legendFormat": "GPU Memory Clock"
    },
    {
     "expr": "sum(DCGM_FI_DEV_MEM_COPY_UTIL) by (Hostname) / count(sum(DCGM_FI_DEV_MEM_COPY_UTIL) by(Hostname, device)) by(Hostname)",
     "legendFormat": "GPU Memory Utilization"
    },
    {
     "expr": "sum(DCGM_FI_PROF_PCIE_TX_BYTES) by (Hostname)",
     "legendFormat": "PCIe TX"
    },
    {
     "expr": "sum(DCGM_FI_PROF_PCIE_RX_BYTES) by (Hostname)",
     "legendFormat": "PCIe RX"
    },
    {
     "expr": "sum(max(DCGM_FI_DEV_POWER_USAGE) by(Hostname, gpu)) by (Hostname)",
     "legendFormat": "GPU Power Usage"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "description": "Потребляемая мощность вычислительных едениц",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(max(DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$node\"}) by(Hostname, gpu)) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    },
    {
     "expr": "sum(max(DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$node\"}) by(Hostname, gpu))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "description": "Утилизация вычислительных едениц",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$node\"}) by(Hostname) / count(sum(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$node\"}) by(Hostname, device)) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU Tensor Core Utilization",
   "type": "timeseries",
   "description": "Утилизация тензорных ядер использующих HMMA*, основанная на продолжительности циклов их работы\n\n*Half matrix multiplication and accumulation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=~\"$node\"}) by(Hostname) / count(sum(DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=~\"$node\"})by(Hostname, gpu)) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Memory Used",
   "type": "timeseries",
   "description": "Потребление кадрового буффера",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{Hostname=~\"$node\"}) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_MEM_COPY_UTIL{Hostname=~\"$node\"}) by(Hostname) / count(sum(DCGM_FI_DEV_MEM_COPY_UTIL{Hostname=~\"$node\"}) by(gpu, Hostname)) by(Hostname)",
     "legendFormat": "{{Hostname}}"
    }
   ]
  },
  {
   "title": "GPU Memory Bandwidth Utilization",
   "type": "timeseries",
   "description": "Утилизация чипов памяти",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_MEM_COPY_UTIL{Hostname=~\"$node\"}) by(Hostname) /  count(sum(DCGM_FI_DEV_MEM_COPY_UTIL{Hostname=~\"$node\"}) by(Hostname, gpu)) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU Graphics Engine Utilization",
   "type": "timeseries",
   "description": "Утилизация графического движка, основанная на продолжительности его работы",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_PROF_GR_ENGINE_ACTIVE{Hostname=~\"$node\"}) by(Hostname)  / count(sum(DCGM_FI_PROF_GR_ENGINE_ACTIVE{Hostname=~\"$node\"}) by(Hostname, gpu)) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU NVLink Bandwidth",
   "type": "timeseries",
   "description": "Скорость передачи данных между графическими процессорами",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{Hostname=~\"$node\"}) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU PCIe Receive",
   "type": "timeseries",
   "description": "Скорость передачи данных через линию шины PCIe RX используя NVML*\n\n*NVIDIA Management Library",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_PROF_PCIE_RX_BYTES{Hostname=~\"$node\"}) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU PCIe Transmit",
   "type": "timeseries",
   "description": "Скорость передачи данных через линию шины PCIe TX используя NVML*\n\n*NVIDIA Management Library",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_PROF_PCIE_TX_BYTES{Hostname=~\"$node\"}) by(Hostname)",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU SM Clock",
   "type": "timeseries",
   "description": "Тактовая частота потокового мультипроцессора",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_SM_CLOCK{Hostname=~\"$node\"}) by(Hostname) * 1000000",
     "legendFormat": "{{ Hostname }}"
    }
   ]
  },
  {
   "title": "GPU Memory Clock",
   "type": "timeseries",
   "description": "Тактовая частота чипов памяти",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_MEM_CLOCK{Hostname=~\"$node\"}) by(Hostname) * 1000000",
     "legendFormat": "[{{ Hostname }}] Device: {{ device}} GPU: {{ gpu }}"
    }
   ]
  }
 ]
}