{
 "title": "GPU Namespaces Overview",
 "tags": [ "GPU" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(DCGM_FI_DEV_POWER_USAGE,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(namespace_service_account:kube_pod_info:, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "table",
   "description": "Сводная таблица утилизации GPU по подам\n\nРесурсы GPU запрашиваются использую PodSpec K8s для ресурса типа `nvidia.com/gpu`",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(label_replace((DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"}), \"namespace\", \"$1\", \"namespace\", \"(.+)\")) by (namespace)",
     "legendFormat": "GPU Utilization"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",resource=\"nvidia_com_gpu\"}) by (namespace)",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"nvidia_com_gpu\"}) by (namespace) - sum(label_replace((DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"}/100), \"namespace\", \"$1\", \"namespace\", \"(.+)\")) by (namespace)",
     "legendFormat": "Over-requested"
    },
    {
     "expr": "sum(label_replace((DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"}/100), \"namespace\", \"$1\", \"namespace\", \"(.+)\")) by (pod) - sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",  resource=\"nvidia_com_gpu\"}) by (namespace) > 0 or vector(0)",
     "legendFormat": "Under-requested"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "description": "Утилизация вычислительных едениц",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{ namespace=\"$namespace\"}) by(namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Over-requested",
   "type": "timeseries",
   "description": "Кол-во вычислительных едениц `nvidia.com/gpu` свыше используемых",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"nvidia_com_gpu\"}) by (namespace) - sum(label_replace((DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"}/100), \"namespace\", \"$1\", \"namespace\", \"(.+)\")) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under-requested",
   "type": "timeseries",
   "description": "Кол-во используемых едениц `nvidia.com/gpu` свыше запрошеных",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "targets": [
    {
     "expr": "sum(label_replace((DCGM_FI_DEV_GPU_UTIL{namespace=~\"$namespace\"}/100), \"namespace\", \"$1\", \"namespace\", \"(.+)\")) by (namespace) - sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"nvidia_com_gpu\"}) by (namespace) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PCIe ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "GPU PCIe Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_PROF_PCIE_RX_BYTES{namespace=\"$namespace\"}) by(namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU PCIe Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_PROF_PCIE_TX_BYTES{namespace=\"$namespace\"}) by(namespace )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SM Clock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "GPU SM Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_SM_CLOCK{namespace=\"$namespace\"}) by(namespace) * 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_MEM_CLOCK{namespace=\"$namespace\"}) by(namespace) * 1000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}