{{/* Copyright 2025 Flant JSC */}}
{{- if eq (include "gpuControlPlane.isEnabled" .) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gpuControlPlane.handlerName" . }}
  namespace: {{ include "gpuControlPlane.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.handlerName" .) "component" "handler")) | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gpuControlPlane.handlerName" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.handlerName" .) "component" "handler")) | nindent 2 }}
rules:
  - apiGroups: [""]
    resources: ["events", "nodes"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: ["gpu.deckhouse.io"]
    resources: ["physicalgpus"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["gpu.deckhouse.io"]
    resources: ["physicalgpus/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["resource.k8s.io"]
    resources: ["deviceclasses", "resourceslices", "resourceclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["resource.k8s.io"]
    resources: ["resourceclaims/status"]
    verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gpuControlPlane.handlerName" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.handlerName" .) "component" "handler")) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gpuControlPlane.handlerName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gpuControlPlane.handlerName" . }}
    namespace: {{ include "gpuControlPlane.namespace" . }}
{{- end }}
