{{/* Copyright 2025 Flant JSC */}}
apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-control-plane-pre-delete-hook
  namespace: {{ include "gpuControlPlane.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "gpu-control-plane-pre-delete-hook")) | nindent 2 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: gpu-control-plane-pre-delete-hook
      {{- include "helm_lib_module_labels" (list . (dict "app" "gpu-control-plane-pre-delete-hook")) | nindent 6 }}
    spec:
      restartPolicy: Never
      serviceAccountName: gpu-control-plane-pre-delete-hook
{{- $podSC := include "helm_lib_module_pod_security_context_run_as_user_deckhouse" . | fromYaml }}
{{- $sc := (get $podSC "securityContext") | default (dict) }}
{{- $_ := set $sc "seccompProfile" (dict "type" "RuntimeDefault") }}
{{- $_ := set $sc "runAsNonRoot" true }}
{{- $_ := set $sc "runAsUser" 64535 }}
{{- $_ := set $sc "runAsGroup" 64535 }}
{{- $_ := set $podSC "securityContext" $sc }}
      {{ toYaml $podSC | nindent 6 }}
      containers:
        - name: gpu-control-plane-pre-delete-hook
          {{- $resources := list
                (dict "gvr" (dict "Group" "nfd.k8s-sigs.io" "Version" "v1alpha1" "Resource" "nodefeaturerules") "name" (include "gpuControlPlane.nodeFeatureRuleName" .))
                (dict "gvr" (dict "Group" "gpu.deckhouse.io" "Version" "v1alpha1" "Resource" "gpudevices") "name" "")
                (dict "gvr" (dict "Group" "gpu.deckhouse.io" "Version" "v1alpha1" "Resource" "gpunodeinventories") "name" "")
                (dict "gvr" (dict "Group" "gpu.deckhouse.io" "Version" "v1alpha1" "Resource" "gpupools") "name" "")
                (dict "gvr" (dict "Group" "gpu.deckhouse.io" "Version" "v1alpha1" "Resource" "clustergpupools") "name" "")
          }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 64535
            runAsGroup: 64535
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          image: "{{ include "helm_lib_module_image" (list . "preDeleteHook" (include "gpuControlPlane.moduleName" .)) }}"
          env:
            - name: WAIT_TIMEOUT
              value: 600s
            - name: RESOURCES
              value: '{{ $resources | toJson }}'
          resources:
            requests:
              {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 14 }}
              cpu: 10m
              memory: 64Mi
      {{- include "helm_lib_tolerations" (tuple . "any-node") | nindent 6 }}
