{{/* Copyright 2025 Flant JSC */}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-control-plane-pre-delete-hook
  namespace: {{ include "gpuControlPlane.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "gpu-control-plane-pre-delete-hook")) | nindent 2 }}
imagePullSecrets:
  - name: gpu-control-plane-module-registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:gpu-control-plane:pre-delete-hook
  {{- include "helm_lib_module_labels" (list . (dict "app" "gpu-control-plane-pre-delete-hook")) | nindent 2 }}
rules:
  - apiGroups:
      - nfd.k8s-sigs.io
    resources:
      - nodefeaturerules
    verbs:
      - get
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:gpu-control-plane:pre-delete-hook
  {{- include "helm_lib_module_labels" (list . (dict "app" "gpu-control-plane-pre-delete-hook")) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:gpu-control-plane:pre-delete-hook
subjects:
  - kind: ServiceAccount
    name: gpu-control-plane-pre-delete-hook
    namespace: {{ include "gpuControlPlane.namespace" . }}
