{{/* Copyright 2025 Flant JSC */}}
{{- if eq (include "gpuControlPlane.isEnabled" .) "true" }}
{{- $resyncPeriod := dig "inventory" "resyncPeriod" "0s" .Values.gpuControlPlane }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "gpuControlPlane.nodeAgentName" . }}
  namespace: {{ include "gpuControlPlane.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.nodeAgentName" .) "component" "node-agent")) | nindent 2 }}
spec:
  selector:
    matchLabels:
      app: {{ include "gpuControlPlane.nodeAgentName" . }}
  template:
    metadata:
      labels:
        app: {{ include "gpuControlPlane.nodeAgentName" . }}
        component: node-agent
        module: {{ include "gpuControlPlane.moduleName" . }}
      annotations:
        kubectl.kubernetes.io/default-container: {{ include "gpuControlPlane.nodeAgentName" . }}
    spec:
      serviceAccountName: {{ include "gpuControlPlane.nodeAgentName" . }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_deckhouse" . | nindent 6 }}
      {{- include "helm_lib_priority_class" (tuple . "system-cluster-critical") | nindent 6 }}
      {{- include "gpuControlPlane.managedNodeTolerations" . | nindent 6 }}
      {{- include "gpuControlPlane.managedNodeAffinity" (list .) | nindent 6 }}
      containers:
        - name: {{ include "gpuControlPlane.nodeAgentName" . }}
          {{- include "helm_lib_module_container_security_context_read_only_root_filesystem" . | nindent 10 }}
          image: {{ include "helm_lib_module_image" (list . "gpuNodeAgent" (include "gpuControlPlane.moduleName" .)) }}
          imagePullPolicy: IfNotPresent
          args:
            - --health-probe-bind-address=:8081
            - --resync-period={{ $resyncPeriod }}
            - --sysfs-path=/host-sys
            - --os-release-path=/host-etc/os-release
            - --pci-ids-paths=/host-usr-share/hwdata/pci.ids,/host-usr-share/misc/pci.ids,/host-usr-share/pci.ids,/host-usr-share/pciids/pci.ids
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
              ephemeral-storage: 50Mi
            limits:
              memory: 128Mi
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
              readOnly: true
            - name: host-os-release
              mountPath: /host-etc/os-release
              readOnly: true
            - name: host-usr-share
              mountPath: /host-usr-share
              readOnly: true
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
        - name: host-os-release
          hostPath:
            path: /etc/os-release
            type: File
        - name: host-usr-share
          hostPath:
            path: /usr/share
{{- end }}
