{{/* Copyright 2025 Flant JSC */}}
{{- if eq (include "gpuControlPlane.isEnabled" .) "true" }}
{{- $controllerName := include "gpuControlPlane.controllerName" . }}
{{- $namespace := include "gpuControlPlane.namespace" . }}
{{- $globalValues := .Values.global | default dict }}
{{- $enabledModules := $globalValues.enabledModules | default (list) }}
{{- if ($enabledModules | has "vertical-pod-autoscaler-crd") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ $controllerName }}
  namespace: {{ $namespace }}
  {{- include "helm_lib_module_labels" (list . (dict "app" $controllerName)) | nindent 2 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $controllerName }}
  updatePolicy:
    # Avoid controller restarts on recommendation updates; apply only on (re)create.
    updateMode: Initial
  resourcePolicy:
    containerPolicies:
      - containerName: {{ $controllerName }}
        minAllowed:
          cpu: 25m
          memory: 128Mi
        maxAllowed:
          cpu: 500m
          memory: 1Gi
        controlledValues: RequestsAndLimits
{{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $controllerName }}
  namespace: {{ $namespace }}
  {{- include "helm_lib_module_labels" (list . (dict "app" $controllerName)) | nindent 2 }}
spec:
  minAvailable: {{ include "helm_lib_is_ha_to_value" (list . 1 0) }}
  selector:
    matchLabels:
      {{- include "gpuControlPlane.selectorLabels" . | nindent 6 }}
{{- end }}
