{{/* Copyright 2025 Flant JSC */}}
{{- if eq (include "gpuControlPlane.isEnabled" .) "true" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpuControlPlane.controllerName" . }}-metrics
  namespace: {{ include "gpuControlPlane.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.controllerName" .))) | nindent 2 }}
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: https-metrics
  selector:
    {{- include "gpuControlPlane.selectorLabels" . | nindent 4 }}
{{- end }}
