{{/* Copyright 2025 Flant JSC */}}
{{- if eq (include "gpuControlPlane.isEnabled" .) "true" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gpu-control-plane-access
  namespace: {{ include "gpuControlPlane.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.moduleName" .))) | nindent 2 }}
rules:
  - apiGroups: ["apps"]
    resources:
      - deployments/prometheus-metrics
      - daemonsets/prometheus-metrics
    resourceNames:
      - {{ include "gpuControlPlane.controllerName" . }}
    verbs: ["get"]
{{- if (.Values.global.enabledModules | default (list) | has "prometheus") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gpu-control-plane-access
  namespace: {{ include "gpuControlPlane.namespace" . }}
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.moduleName" .))) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gpu-control-plane-access
subjects:
  - kind: User
    name: d8-monitoring:scraper
  - kind: ServiceAccount
    name: prometheus
    namespace: d8-monitoring
{{- end }}
{{- end }}
