{{/* Copyright 2025 Flant JSC */}}
apiVersion: v1
kind: Namespace
metadata:
  {{- include "helm_lib_module_labels" (list . (dict "prometheus.deckhouse.io/rules-watcher-enabled" "true")) | nindent 2 }}
  name: {{ include "gpuControlPlane.namespace" . }}
---
{{- include "helm_lib_kube_rbac_proxy_ca_certificate" (list . (include "gpuControlPlane.namespace" .)) }}
