{{/* Copyright 2025 Flant JSC */}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "gpuControlPlane.namespace" . }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  {{- include "helm_lib_module_labels" (list . (dict "prometheus.deckhouse.io/rules-watcher-enabled" "true" "app.kubernetes.io/managed-by" (.Release.Service | default "Helm"))) | nindent 2 }}
---
{{- include "helm_lib_kube_rbac_proxy_ca_certificate" (list . (include "gpuControlPlane.namespace" .)) }}
