{{/* Copyright 2025 Flant JSC */}}
{{- if eq (include "gpuControlPlane.isEnabled" .) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.controllerName" .))) | nindent 2 }}
  name: {{ include "gpuControlPlane.controllerName" . }}
  namespace: {{ include "gpuControlPlane.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.controllerName" .))) | nindent 2 }}
  name: {{ include "gpuControlPlane.controllerName" . }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
  - apiGroups: ["gpu.deckhouse.io"]
    resources: ["gpudevices"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["gpu.deckhouse.io"]
    resources: ["gpudevices/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["gpu.deckhouse.io"]
    resources: ["gpunodeinventories"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["gpu.deckhouse.io"]
    resources: ["gpunodeinventories/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["nfd.k8s-sigs.io"]
    resources: ["nodefeatures"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["gpu.deckhouse.io"]
    resources: ["gpupools"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["gpu.deckhouse.io"]
    resources: ["gpupools/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["deckhouse.io"]
    resources: ["moduleconfigs"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["deckhouse.io"]
    resources: ["moduleconfigs/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- include "helm_lib_module_labels" (list . (dict "app" (include "gpuControlPlane.controllerName" .))) | nindent 2 }}
  name: {{ include "gpuControlPlane.controllerName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gpuControlPlane.controllerName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gpuControlPlane.controllerName" . }}
    namespace: {{ include "gpuControlPlane.namespace" . }}
{{- end }}
