{{/* Copyright 2025 Flant JSC */}}
{{/* Use module specific dockercfg if set. Fallback to global dockercfg when module embedded. */}}
{{- $moduleValues := .Values.gpuControlPlane | default dict }}
{{- $dockercfg := dig "registry" "dockercfg" "<missing>" $moduleValues }}
{{- if eq $dockercfg "<missing>" }}
  {{- $dockercfg = dig "modulesImages" "registry" "dockercfg" "" .Values.global }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gpu-control-plane-module-registry
  namespace: {{ include "gpuControlPlane.namespace" . }}
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockercfg | quote }}
