// Copyright 2025 Flant JSC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

var exitFunc = os.Exit

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		exitFunc(1)
	}
}

func run(args []string) error {
	if len(args) != 2 {
		return fmt.Errorf("usage: %s <pci.ids> <output.go>", filepath.Base(os.Args[0]))
	}

	deviceNames, err := parseDevices(args[0])
	if err != nil {
		return err
	}
	if len(deviceNames) == 0 {
		return fmt.Errorf("no NVIDIA devices gathered from %s", args[0])
	}

	return writeDevices(args[1], deviceNames)
}

func parseDevices(path string) (map[string]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open input file: %w", err)
	}
	defer func() { _ = file.Close() }()

	deviceNames := make(map[string]string)
	scanner := bufio.NewScanner(file)
	var currentVendor string

	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		switch {
		case !strings.HasPrefix(line, "\t"):
			fields := strings.Fields(line)
			if len(fields) == 0 {
				continue
			}
			currentVendor = strings.ToLower(fields[0])
		case strings.HasPrefix(line, "\t") && !strings.HasPrefix(line, "\t\t") && currentVendor == "10de":
			trimmed := strings.TrimSpace(line)
			fields := strings.Fields(trimmed)
			if len(fields) == 0 {
				continue
			}
			deviceID := strings.ToLower(fields[0])
			name := strings.TrimSpace(trimmed[len(fields[0]):])
			if name == "" {
				continue
			}
			key := fmt.Sprintf("%s:%s", currentVendor, deviceID)
			deviceNames[key] = normalizeName(name)
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan pci.ids: %w", err)
	}

	return deviceNames, nil
}

func writeDevices(path string, deviceNames map[string]string) error {
	var buf bytes.Buffer
	buf.WriteString("// Copyright 2025 Flant JSC\n")
	buf.WriteString("//\n")
	buf.WriteString("// Licensed under the Apache License, Version 2.0 (the \"License\");\n")
	buf.WriteString("// you may not use this file except in compliance with the License.\n")
	buf.WriteString("// You may obtain a copy of the License at\n")
	buf.WriteString("//\n")
	buf.WriteString("//     http://www.apache.org/licenses/LICENSE-2.0\n")
	buf.WriteString("//\n")
	buf.WriteString("// Unless required by applicable law or agreed to in writing, software\n")
	buf.WriteString("// distributed under the License is distributed on an \"AS IS\" BASIS,\n")
	buf.WriteString("// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n")
	buf.WriteString("// See the License for the specific language governing permissions and\n")
	buf.WriteString("// limitations under the License.\n\n")
	buf.WriteString("// Code generated by cmd/generate; DO NOT EDIT.\n")
	buf.WriteString("// Generated at " + time.Now().UTC().Format(time.RFC3339) + "\n\n")
	buf.WriteString("package nvidia\n\n")
	buf.WriteString("// DeviceNames maps vendor:device PCI identifiers to human readable GPU names.\n")
	buf.WriteString("var DeviceNames = map[string]string{\n")

	keys := make([]string, 0, len(deviceNames))
	for key := range deviceNames {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	for _, key := range keys {
		name := deviceNames[key]
		buf.WriteString(fmt.Sprintf("\t%q: %s,\n", key, strconv.Quote(name)))
	}
	buf.WriteString("}\n")

	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write output file: %w", err)
	}
	return nil
}

func normalizeName(name string) string {
	name = strings.TrimSpace(name)
	name = strings.TrimPrefix(name, "NVIDIA ")
	return name
}
